version: '2'
services:
    laravel:
        image: shivergard/docker-webserver
        ports:
            - 5500:80
            - 5586:86
        volumes:
            - ./laravel:/var/www
            - ./storage:/var/www/storage
    pandas:
        build: ./build/pandas
        volumes:
            - ./storage:/opt/storage
            - ./:/opt/project
        command: tail -f /dev/null
        env_file:
            - ./laravel/.env
