version: '2'
services:
    laravel:
        image: shivergard/docker-webserver
        ports:
            - 5500:80
            - 5586:86
        volumes:
            - ./laravel:/var/www
    pandas:
        build: ./build/pandas
        volumes:
            - ./:/opt/storage
        command: tail -f /dev/null
    city_runner:
        build: ./build/city_runner
        volumes:
            - ./storage:/opt/storage
        ports:
            - 8050:8080
        restart: always
        env_file:
            - ./.env
